language: python
python:
 - "2.7"
virtualenv:
    system_site_packages: true
before_install:
 - sudo apt-get install gir1.2-gtk-3.0 gir1.2-vte-2.90 python-gi python-gobject python-gobject-2 python-gobject-dev
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
install:
 - sudo python setup.py install
script:
 - python test.py
